apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: litefunctions
    meta.helm.sh/release-namespace: litefunctions
  creationTimestamp: "2026-01-22T11:27:38Z"
  generation: 1
  labels:
    app: gitea
    app.kubernetes.io/instance: litefunctions
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.24.6
    helm.sh/chart: gitea-12.4.0
    version: 1.24.6
  name: litefunctions-gitea
  namespace: litefunctions
  resourceVersion: "1327277"
  uid: c516b8c0-da9b-4794-9c32-2c6652d4b33c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: litefunctions
      app.kubernetes.io/name: gitea
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: bc4ad9947028833beb6b814305df8c8d779ccd637a8a1e0b4a661e855c895848
      creationTimestamp: null
      labels:
        app: gitea
        app.kubernetes.io/instance: litefunctions
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: gitea
        app.kubernetes.io/version: 1.24.6
        helm.sh/chart: gitea-12.4.0
        version: 1.24.6
    spec:
      containers:
      - env:
        - name: SSH_LISTEN_PORT
          value: "2222"
        - name: SSH_PORT
          value: "22"
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        - name: TMPDIR
          value: /tmp/gitea
        - name: HOME
          value: /data/gitea/git
        image: docker.gitea.com/gitea:1.24.6-rootless
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 200
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        name: gitea
        ports:
        - containerPort: 2222
          name: ssh
          protocol: TCP
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: temp
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /usr/sbinx/init_directory_structure.sh
        env:
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        image: docker.gitea.com/gitea:1.24.6-rootless
        imagePullPolicy: IfNotPresent
        name: init-directories
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/sbinx
          name: init
        - mountPath: /tmp
          name: temp
        - mountPath: /data
          name: data
      - command:
        - /usr/sbinx/config_environment.sh
        env:
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        - name: TMP_EXISTING_ENVS_FILE
          value: /tmp/existing-envs
        - name: ENV_TO_INI_MOUNT_POINT
          value: /env-to-ini-mounts
        image: docker.gitea.com/gitea:1.24.6-rootless
        imagePullPolicy: IfNotPresent
        name: init-app-ini
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/sbinx
          name: config
        - mountPath: /tmp
          name: temp
        - mountPath: /data
          name: data
        - mountPath: /env-to-ini-mounts/inlines/
          name: inline-config-sources
      - command:
        - /usr/sbinx/configure_gitea.sh
        env:
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        - name: HOME
          value: /data/gitea/git
        - name: GITEA_ADMIN_USERNAME
          value: gitea_admin
        - name: GITEA_ADMIN_PASSWORD
          value: r8sA8CPHD9!bt6d
        - name: GITEA_ADMIN_PASSWORD_MODE
          value: keepUpdated
        image: docker.gitea.com/gitea:1.24.6-rootless
        imagePullPolicy: IfNotPresent
        name: configure-gitea
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/sbinx
          name: init
        - mountPath: /tmp
          name: temp
        - mountPath: /data
          name: data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - name: init
        secret:
          defaultMode: 110
          secretName: litefunctions-gitea-init
      - name: config
        secret:
          defaultMode: 110
          secretName: litefunctions-gitea
      - name: inline-config-sources
        secret:
          defaultMode: 420
          secretName: litefunctions-gitea-inline-config
      - emptyDir: {}
        name: temp
      - name: data
        persistentVolumeClaim:
          claimName: gitea-shared-storage
status:
  conditions:
  - lastTransitionTime: "2026-01-22T11:27:38Z"
    lastUpdateTime: "2026-01-22T11:27:38Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-01-22T11:27:38Z"
    lastUpdateTime: "2026-01-22T11:27:38Z"
    message: ReplicaSet "litefunctions-gitea-67db88cdd7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
