{{- if .Values.gitea.enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: litefunctions-admin-token
type: Opaque
stringData:
  token: "{{ randAlphaNum 40 }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: litefunctions-registration-token
type: Opaque
stringData:
  token: "{{ randAlphaNum 40 }}"
{{- end}}
