#TODO: avoid redundant manifest, kustomize manager.yaml from operator config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "litefunctions.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "litefunctions.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "litefunctions.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        {{- include "litefunctions.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /operator
        args:
        - manager
        - --leader-elect
        image: {{ .Values.images.operator }} 
        env:
        - name: GRPC_PORT
          value: "50051"
        {{- if .Values.operator.registry }}
        - name: REGISTRY
          value: {{ .Values.operator.registry | quote }}
        {{- end }}
        {{- if .Values.operator.registry_user }}
        - name: REGISTRY_USER
          value: {{ .Values.operator.registry_user | quote }}
        {{- else if .Values.operator.vcs_user }}
        - name: REGISTRY_USER
          value: {{ .Values.operator.vcs_user | quote }}
        {{- end }}
        {{- if .Values.operator.pull_secret }}
        - name: PULL_SECRET
          value: {{ .Values.operator.pull_secret | quote }}
        {{- end }}
        {{- if .Values.operator.db_secret_name }}
        - name: DB_SECRET_NAME
          value: {{ .Values.operator.db_secret_name | quote }}
        {{- end }}
        {{- if .Values.operator.db_secret_key }}
        - name: DB_SECRET_KEY
          value: {{ .Values.operator.db_secret_key | quote }}
        {{- end }}
        {{- if .Values.operator.redis_url }}
        - name: REDIS_URL
          value: {{ .Values.operator.redis_url | quote }}
        {{- end }}
        {{- if .Values.operator.nats_url }}
        - name: NATS_URL
          value: {{ .Values.operator.nats_url | quote }}
        {{- end }}
        {{- if .Values.operator.deprovision_duration }}
        - name: DEPROVISION_DURATION
          value: {{ .Values.operator.deprovision_duration | quote }}
        {{- end }}
        {{- if .Values.operator.keep_warm_duration }}
        - name: KEEP_WARM_DURATION
          value: {{ .Values.operator.keep_warm_duration | quote }}
        {{- end }}
        name: litefunctions-manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "litefunctions.labels" . | nindent 4 }}
  name: litefunctions-operator
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
    nodePort: {{ .Values.operator.service.nodePort }}
  selector:
    control-plane: controller-manager
    {{- include "litefunctions.selectorLabels" . | nindent 4 }}
  type: {{ .Values.ingestor.service.type }}
---
