#TODO: avoid redundant manifest, kustomize manager.yaml from operator config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "litefunctions.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "litefunctions.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "litefunctions.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        {{- include "litefunctions.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        image: {{ .Values.images.operator }} 
        env:
        {{- if .Values.operator.registry }}
        - name: REGISTRY
          value: {{ .Values.operator.registry | quote }}
        {{- end }}
        {{- if .Values.operator.vcs_user }}
        - name: VCS_USER
          value: {{ .Values.operator.vcs_user | quote }}
        {{- end }}
        {{- if .Values.operator.pull_secret }}
        - name: PULL_SECRET
          value: {{ .Values.operator.pull_secret | quote }}
        {{- end }}
        {{- if .Values.operator.db_secret_name }}
        - name: DB_SECRET_NAME
          value: {{ .Values.operator.db_secret_name | quote }}
        {{- end }}
        {{- if .Values.operator.db_secret_key }}
        - name: DB_SECRET_KEY
          value: {{ .Values.operator.db_secret_key | quote }}
        {{- end }}
        {{- if .Values.operator.redis_url }}
        - name: REDIS_URL
          value: {{ .Values.operator.redis_url | quote }}
        {{- end }}
        {{- if .Values.operator.nats_url }}
        - name: NATS_URL
          value: {{ .Values.operator.nats_url | quote }}
        {{- end }}
        name: litefunctions-manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
