global:
  DNS: localhost
server:
  replicas: 1
  image:
    registry: docker.io
    repository: ashupednekar535/litewebservices-portal
    tag: "a57a602"
  db:
    secret: db-pguser-db
    key: pgbouncer-uri
  vcs:
    secret: vcs-secret
    key: token
  probes:
    enabled: false
ingress:
  host: lws.ashudev.in
  issuer: letsencrypt
