title = "LiteFunctions"
description = "Kubernetes-native functions platform with no vendor lock-in and no language lock-in."
images = ["cover.png"]
mainSections = ["docs"]

[params]
  google_fonts = [
    ["Manrope", "300,400,500,600,700"],
    ["Newsreader", "400,600,700"],
    ["Fira Code", "400,500,600"]
  ]
  sans_serif_font = "Manrope"
  secondary_font = "Newsreader"
  mono_font = "Fira Code"
  logo = "favicon.svg"
  logo_dark = "favicon.svg"
  logo_light = "favicon.svg"

  [params.social]
    github = "https://github.com/ashupednekar/litefunctions"

  [params.docs]
    title = "LiteFunctions"
    pathName = "docs"
    themeColor = "blue"
    darkMode = true
    prism = true
    prismTheme = "dracula"
    repo = "https://github.com/ashupednekar/litefunctions"
    repoBranch = "main"
    editPage = false
    lastMod = false
    sidebarIcons = true
    breadcrumbs = true
    toc = true

  [params.footer]
    copyright = "Copyright (c) 2024-2026 LiteFunctions"
