apiVersion: v1
entries:
  litefunctions:
    - apiVersion: v2
      name: litefunctions
      version: 0.1.0
      description: A Helm chart for Kubernetes
      type: application
      appVersion: "1.16.0"
      urls:
        - oci://ghcr.io/ashupednekar/charts/litefunctions
