apiVersion: apps.ashupednekar.github.io/v1
kind: Function
metadata:
  name: onego
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
spec:
  name: one
  project: projectx
  language: go
  git_creds: vcs-secret

